### ISSUE TITLE
ERROR npm ERR! Invalid version: 2024.5.8.0:  My second release failed and I don't know why

### ISSUE THREAD

**Issue by webmatrixxxl** [casmith/release-it-calver-plugin#47]
I have done a release once with release-it and calver-plugin. My second release failed. Nothing in the configuration was changed.

It turned out that the release version would fail if the `format` configuration property included (major, minor, patch) e.g. 'yyyy.mm.dd.minor' **AND** the day of the date is between 1-9. e.g. '2024-05-08'  will fail but '2024-05-11' will work.

If the format is 'yyyy.mm.dd'  i.e. without (major, minor, patch) it will work.

I'm using package.json to read/write the version.

🚀 Let's release xxx (2024.4.1-9.0...2024.5.8.0)

```
module.exports = {
  git: {
    commitMessage: 'chore: release v${version} [ci skip]'
  },
  plugins: {
    '@csmith/release-it-calver-plugin': {
      format: 'yyyy.mm.dd.minor',
      increment: 'calendar'
    },
  }
}
```

`terminal`
```
ERROR npm error Invalid version: 2024.5.8.0

npm error A complete log of this run can be found in: /Users/myuser/.npm/_logs/2024-05-08T23_36_05_823Z-debug-0.log
```

`/Users/myuser/.npm/_logs/2024-05-08T23_36_05_823Z-debug-0.log`
```
0 verbose cli /Users/myuser/.nvm/versions/node/v18.20.2/bin/node /Users/myuser/.nvm/versions/node/v18.20.2/bin/npm
1 info using npm@10.7.0
2 info using node@v18.20.2
3 silly config:load:file:/Users/myuser/.nvm/versions/node/v18.20.2/lib/node_modules/npm/npmrc
4 silly config:load:file:/Users/myuser/www/my-project-name/.npmrc
5 silly config:load:file:/Users/myuser/.npmrc
6 silly config:load:file:/Users/myuser/.nvm/versions/node/v18.20.2/etc/npmrc
7 verbose title npm version 2024.5.8.0
8 verbose argv "version" "2024.5.8.0" "--no-git-tag-version"
9 verbose logfile logs-max:10 dir:/Users/myuser/.npm/_logs/2024-05-08T23_36_05_823Z-
10 verbose logfile /Users/myuser/.npm/_logs/2024-05-08T23_36_05_823Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 verbose stack Error: Invalid version: 2024.5.8.0
12 verbose stack     at module.exports (/Users/myuser/.nvm/versions/node/v18.20.2/lib/node_modules/npm/node_modules/libnpmversion/lib/version.js:39:25)
12 verbose stack     at module.exports (/Users/myuser/.nvm/versions/node/v18.20.2/lib/node_modules/npm/node_modules/libnpmversion/lib/index.js:22:10)
12 verbose stack     at async Version.change (/Users/myuser/.nvm/versions/node/v18.20.2/lib/node_modules/npm/lib/commands/version.js:75:21)
12 verbose stack     at async module.exports (/Users/myuser/.nvm/versions/node/v18.20.2/lib/node_modules/npm/lib/cli/entry.js:74:5)
13 verbose cwd /Users/myuser/www/my-project-name
14 verbose Darwin 23.5.0
15 verbose node v18.20.2
16 verbose npm  v10.7.0
17 error Invalid version: 2024.5.8.0
18 verbose exit 1
19 verbose code 1
20 error A complete log of this run can be found in: /Users/myuser/.npm/_logs/2024-05-08T23_36_05_823Z-debug-0.log
```

**Comment by tb-b** [comment]
Can confirm I'm running into the same problem

**Comment by casmith** [comment]
This is an npm limitation, not a plugin bug. npm validates versions using semver, and `2024.5.8.0` has 4 numeric dot-separated segments which isn't valid semver. Some 4-segment versions appear to work by accident depending on the specific numbers, but it's not reliable.

The good news is that calver 24.x (coming in the next release) uses `-` as the date separator, producing versions like `2024-5-8.0` instead of `2024.5.8.0`. This is semver-compatible since the dashes make the date portion parse as a prerelease identifier.

In the meantime, your options are:
- Use `yyyy.mm.dd` without minor (3 segments is valid semver)
- Skip the npm version bump with `"npm": { "skipChecks": true }` in your release-it config if you don't publish to npm

**Comment by casmith** [comment]
Update: we ended up converting calver 24.x output back to dot-separated format (e.g. `2026.3.5`) for broader npm compatibility. This means the 4-segment day format (`2026.5.8.0`) will still have the same semver limitation.

If you need day-level versioning with npm, use `yyyy.mm.dd` without minor (3 segments), or set `"npm": { "skipChecks": true }` if you don't publish to npm.

If you prefer the dash-separated format and don't need npm compatibility, you can opt in with the `separator` option:

```json
"@csmith/release-it-calver-plugin": {
    "cycle": "day",
    "separator": "-"
}
```

This produces versions like `2026-3-24.0`.
